- hosts: localhost
  vars:
    home:       "{{ lookup('env', 'HOME') }}"
    source_key: "./.ssh/id_rsa_github"
    dest_key:   "{{ home }}/.ssh/id_rsa_github"
    personal:   "{{ home }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - 
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/core-setup.yml
    # - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/nvim-setup.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/productivity-tools.yml
    # - include_tasks: tasks/lsp.yml
    - include_tasks: tasks/node-setup.yml
    # - include_tasks: tasks/npm-packages.yml
    # - include_tasks: tasks/slack-setup.yml
    # - include_tasks: tasks/personal-projects.yml
    # - include_tasks: tasks/brave.yml
    # - include_tasks: tasks/debugger.yml
