- hosts: localhost
  gather_facts: yes  # Gather host information, e.g. os_family
  vars_files:
    - packages.yml
  vars:
    home:       "{{ lookup('env', 'HOME') }}"
    work:       "{{ home }}/work"
    personal:   "{{ home }}/personal"
    source_key: "./.ssh/id_rsa_github"
    dest_key:   "{{ home }}/.ssh/id_rsa_github"


  pre_tasks:

    - name: Check OS Type
      debug:
        msg: "Detected OS: {{ ansible_facts['os_family'] }}"

    - name: Ensure XDG and other directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ home }}/.config"
        - "{{ home }}/.local/bin"
        - "{{ home }}/.local/lib"
        - "{{ home }}/.local/share"
        - "{{ personal }}"
        - "{{ work }}"

    - name: Update Apt
      when: ansible_facts['os_family'] == "Debian"
      become: true
      apt:
        update_cache: true

    - name: Update Homebrew
      when: ansible_facts['os_family'] == "Darwin"
      homebrew:
        update_homebrew: true

  tasks:

    - name: Set package list based on OS
      set_fact:
        package_list: >-
          {{ common + (debian if ansible_facts['os_family'] == 'Debian'
                       else macos if ansible_facts['os_family'] == 'Darwin'
                       else []) }}

    - name: Install packages on Debian-based systems
      become: yes
      apt:
        name: "{{ package_list }}"
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install packages on macOS
      homebrew:
        name: "{{ package_list }}"
        state: present
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Run common tasks
      block:
        # TODO: ssh.yml is only setup for git tbh maybe combine
        - include_tasks: tasks/ssh.yml
        - include_tasks: tasks/git-setup.yml
        - include_tasks: tasks/nvim-setup.yml
        - include_tasks: tasks/dotfiles.yml
        - include_tasks: tasks/tpm.yml
        # TODO: Remove unused files
        #- include_tasks: tasks/productivity-tools.yml
        #- include_tasks: tasks/node-setup.yml

    # TODO: Write Debian only tasks, e.g. running custom install scripts like pyenv
    # - name: Run Debian tasks
    #   block:
    #     - include_tasks: tasks/ssh.yml

