- hosts: localhost
  gather_facts: yes  # Gather host information, e.g. os_family
  vars:
    home:       "{{ lookup('env', 'HOME') }}"
    repos:       "{{ home }}/repos"
    source_key: "./.ssh/id_rsa_github"
    dest_key:   "{{ home }}/.ssh/id_rsa_github"

  tasks:
    - name: Check OS Type
      debug:
        msg: "Detected OS: {{ ansible_facts['os_family'] }}"

    - name: Run tasks for Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      block:
        - name: Update Apt
          become: true
          apt:
            force_apt_get: true
            update_cache: true
            state: present
          tags:
            - install
            - core

        #- include_tasks: tasks/xdg-filespec.yml
        - include_tasks: tasks/ssh.yml
        - include_tasks: tasks/git-setup.yml
        - include_tasks: tasks/core-setup.yml
        - include_tasks: tasks/nvim-setup.yml
        - include_tasks: tasks/dotfiles.yml
        - include_tasks: tasks/productivity-tools.yml
        - include_tasks: tasks/node-setup.yml

    - name: Run tasks for macOS
      when: ansible_facts['os_family'] == "Darwin"
      block:
        #- include_tasks: tasks/xdg-filespec.yml
        # ssh.yml is only setup for git tbh
        - include_tasks: tasks/ssh.yml
        - include_tasks: tasks/git-setup.yml
        - include_tasks: tasks/nvim-setup.yml
