- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:maxestorr/.dotfiles.git'
    dest: "{{ home }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow.sh
  tags:
    - install
    - dotfiles
    - stow

