# TODO: This should be done elsewhere and put into a stat
# since building neovim is OS indepedent but prereqs aren't
- name: Install Neovim build prereq's
  when: ansible_facts['os_family'] == "Darwin"
  homebrew:
    name:
      - ninja 
      - cmake
      - gettext
      - curl
    state: present

- name: Clone Neovim
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ repos }}/neovim"
    update: yes
    force: yes
  register: git_status

- name: Display update status
  debug:
    msg: "Neovim repo was updated!"
  when: git_status.after != git_status.before

- name: Build & install neovim
  when: git_status.after != git_status.before
  shell: |
    cd {{ repos }}/neovim
    rm -r build/
    make CMAKE_BUILD_TYPE=Release
    make CMAKE_INSTALL_PREFIX={{ home }}/.local/lib/neovim install
  tags:
    - install
    - neovim

- name: Symlink Neovim binary to ~/.local/bin/nvim
  file:
    src: "{{ home }}/.local/lib/neovim/bin/nvim"
    dest: "{{ home }}/.local/bin/nvim"
    state: link
    force: yes

