- name: Install Neovim Debian build prereq's
  when: ansible_facts['os_family'] == "Debian"
  become: true
  apt:
    name:
      - ninja-build
      - cmake
      - gettext
      - curl
    state: present

- name: Install Neovim build prereq's
  when: ansible_facts['os_family'] == "Darwin"
  homebrew:
    name:
      - ninja 
      - cmake
      - gettext
      - curl
    state: present

- name: Clone Neovim
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ repos }}/neovim"
    update: yes
    force: yes
  register: git_status

- name: Display Neovim update status
  debug:
    msg: |
      {% if git_status.after != git_status.before %}
      Neovim repo was updated! Latest commit: {{ git_status.after }}
      {% else %}
      No update - already up to date. Current commit: {{ git_status.before }}
      {% endif %}

- name: Build & install neovim
  when: git_status.after != git_status.before
  shell: |
    cd {{ repos }}/neovim
    rm -r build/
    make CMAKE_BUILD_TYPE=Release
    make CMAKE_INSTALL_PREFIX={{ home }}/.local/lib/neovim install
  tags:
    - install
    - neovim

- name: Symlink Neovim binary to ~/.local/bin/nvim
  file:
    src: "{{ home }}/.local/lib/neovim/bin/nvim"
    dest: "{{ home }}/.local/bin/nvim"
    state: link
    force: yes

