- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "kdenlive", "gimp", "xclip", "screenkey", "tldr", "ripgrep" ]
  tags:
    - install
    - productivity

- name: Does TPM exist?
  stat:
    path: "{{ home }}/.tmux/plugins/tpm"
  register: tpm_git
  tags:
    - install
    - productivity

- name: Cloning tmux package manager (tpm)
  ansible.builtin.git:
    repo: 'git clone https://github.com/tmux-plugins/tpm'
    dest: "{{ home }}/.tmux/plugins/tpm"
  tags:
    - install
    - productivity
  when: tpm_git.stat.exists == False

# - name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
#   become: true
#   apt_repository:
#    repo: ppa:kdenlive/kdenlive-stable
#    state: present
#    update_cache: True
#   tags:
#     - install
#     - productivity
# 
# - name: shutter ppa (ppa:linuxuprising/shutter)
#   become: true
#   apt_repository:
#    repo: ppa:linuxuprising/shutter
#    state: present
#    update_cache: True
#   tags:
#     - install
#     - productivity
