- name: Ensure .ssh directory exists
  file:
    dest: "{{ home }}/.ssh"
    mode: "0700"
    state: directory
  tags:
    - install
    - ssh

- name: Install ssh private keys
  copy:
    src: "./.ssh/{{ item }}"
    dest: "{{ home }}/.ssh/{{ item }}"
    mode: "0600"
  loop: "{{ ssh_keys }}"
  tags:
    - install
    - ssh

- name: Install ssh public keys
  copy:
    src: "./.ssh/{{ item }}.pub"
    dest: "{{ home }}/.ssh/{{ item }}.pub"
    mode: "0644"
  loop: "{{ ssh_keys }}"
  tags:
    - install
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ home }}/.ssh/*.pub"
